"""
Shared HTML shell for the Lodge's standalone reports (structural + reasoning).

Both reports are single self-contained .html files meant to be opened
directly in a browser — no server, no external assets, no build step. This
module only supplies the page shell and shared CSS so the two report
generators don't duplicate styling; it has no opinion about report content.
"""

import html
from urllib.parse import quote

CSS = """
:root {
  --ink: #2a2622;
  --ink-soft: #5a5349;
  --paper: #faf7f0;
  --panel: #ffffff;
  --line: #e2dccd;
  --accent: #6b3f2a;
  --accent-soft: #9c6b4c;
  --disclaimer-bg: #fff3d6;
  --disclaimer-border: #c9962f;
  --good: #3f6b3f;
  --bad: #a13b3b;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 0 0 4rem 0;
  background: var(--paper);
  color: var(--ink);
  font-family: -apple-system, "Segoe UI", Georgia, "Iowan Old Style", serif;
  line-height: 1.55;
}
.wrap {
  max-width: 920px;
  margin: 0 auto;
  padding: 0 1.5rem;
}
header.page {
  background: var(--accent);
  color: #fbf3e6;
  padding: 2.2rem 0 1.6rem 0;
  margin-bottom: 2rem;
}
header.page .wrap h1 {
  margin: 0 0 0.3rem 0;
  font-size: 1.7rem;
  font-weight: 600;
}
header.page .wrap .meta {
  color: #ecd9bd;
  font-size: 0.95rem;
}
h2 {
  font-size: 1.25rem;
  border-bottom: 2px solid var(--line);
  padding-bottom: 0.35rem;
  margin-top: 2.4rem;
}
h3 {
  font-size: 1.05rem;
  color: var(--accent);
  margin-top: 1.6rem;
}
p { max-width: 72ch; }
.summary {
  font-size: 1.08rem;
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 6px;
  padding: 1.1rem 1.3rem;
}
.disclaimer {
  background: var(--disclaimer-bg);
  border-left: 5px solid var(--disclaimer-border);
  border-radius: 4px;
  padding: 1rem 1.3rem;
  margin: 1.4rem 0;
  font-size: 0.98rem;
}
.disclaimer strong { color: #6b4c00; }
table {
  border-collapse: collapse;
  width: 100%;
  margin: 0.8rem 0 1.6rem 0;
  background: var(--panel);
  font-size: 0.95rem;
}
caption {
  caption-side: top;
  text-align: left;
  font-weight: 600;
  color: var(--accent);
  padding-bottom: 0.3rem;
}
th, td {
  border: 1px solid var(--line);
  padding: 0.45rem 0.75rem;
  text-align: right;
}
th:first-child, td:first-child { text-align: left; }
thead th {
  background: #f1e9d8;
  color: var(--ink);
  font-weight: 600;
}
tbody tr:nth-child(even) { background: #fbf8f1; }
.note {
  color: var(--ink-soft);
  font-size: 0.88rem;
  margin: -0.9rem 0 1.6rem 0;
}
.pill {
  display: inline-block;
  padding: 0.1rem 0.55rem;
  border-radius: 999px;
  font-size: 0.82rem;
  font-weight: 600;
}
.pill.ok { background: #e2ecdd; color: var(--good); }
.pill.bad { background: #f4dede; color: var(--bad); }
footer.page {
  margin-top: 3rem;
  padding-top: 1rem;
  border-top: 1px solid var(--line);
  color: var(--ink-soft);
  font-size: 0.85rem;
}
@media (prefers-color-scheme: dark) {
  :root {
    --ink: #ece6d9;
    --ink-soft: #b8b0a0;
    --paper: #201d18;
    --panel: #2a2620;
    --line: #453f34;
    --accent: #d99b6c;
    --accent-soft: #c98a58;
    --disclaimer-bg: #3a2f14;
    --disclaimer-border: #d9a53a;
    --good: #8fbf8f;
    --bad: #e08a8a;
  }
  header.page { background: #3a2416; color: #f3e6d4; }
  header.page .wrap .meta { color: #d9c2a0; }
  thead th { background: #362f22; }
  tbody tr:nth-child(even) { background: #262219; }
  .disclaimer strong { color: #f0c874; }
}
"""


def favicon_link(emoji):
    """An emoji as the tab icon, inline — the reports have no asset directory
    to put a .ico in, and a browser asking for /favicon.ico on a static host
    is a 404 in every reader's console."""
    svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">'
           f'<text y=".9em" font-size="90">{html.escape(emoji)}</text></svg>')
    return f'<link rel="icon" href="data:image/svg+xml,{quote(svg)}">'


def html_shell(title, favicon_emoji, header_title, header_meta, body_html):
    """title: <title> text. header_title/header_meta: the on-page banner.
    body_html: everything below the banner, already-escaped where needed."""
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
{favicon_link(favicon_emoji)}
<style>{CSS}</style>
</head>
<body>
<header class="page"><div class="wrap">
  <h1>{header_title}</h1>
  <div class="meta">{header_meta}</div>
</div></header>
<div class="wrap">
{body_html}
<footer class="page">Generated by the Lodge simulation harness. Self-contained — no external assets.</footer>
</div>
</body>
</html>"""


def esc(x):
    return html.escape(str(x))


def table(headers, rows, caption=None, note=None):
    """headers: list of column labels. rows: list of lists (already strings)."""
    out = ["<table>"]
    if caption:
        out.append(f"<caption>{esc(caption)}</caption>")
    out.append("<thead><tr>" + "".join(f"<th>{esc(h)}</th>" for h in headers) + "</tr></thead>")
    out.append("<tbody>")
    for row in rows:
        out.append("<tr>" + "".join(f"<td>{esc(c)}</td>" for c in row) + "</tr>")
    out.append("</tbody></table>")
    if note:
        out.append(f'<p class="note">{esc(note)}</p>')
    return "\n".join(out)
