"""Re-skins already-generated standalone reports to the current shell CSS.

    python3 scripts/restyle_reports.py [--check]

The structural and reasoning reports are one-shot outputs: each is the record
of a run that happened, and re-running the simulation to restyle it would
produce different numbers. But every one of them embeds a verbatim copy of
report_common.CSS in a single <style> block, so the styling can be swapped
without touching a single figure — which is what this does.

Only files that html_shell produced are touched, identified by its footer
line. The dashboard's own four pages are skipped: make_index.py regenerates
those from source.

--check reports what would change and exits 1 if anything is stale, which is
what CI wants after a change to report_common.CSS.
"""

import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
for _p in (_REPO, _HERE):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import dashboard as dash
from report_common import CSS

REPORTS_DIR = os.path.join(_REPO, "reports")

# html_shell's footer. Its presence is what makes a file a standalone report
# rather than a hand-written page that happens to live in reports/.
SHELL_MARK = "Generated by the Lodge simulation harness."

STYLE_RE = re.compile(r"(<style>)(.*?)(</style>)", re.S)


def restyle(path):
    """Swap the file's <style> body for the current CSS. Returns True if the
    file needed changing."""
    with open(path, encoding="utf-8") as f:
        doc = f.read()
    if SHELL_MARK not in doc:
        return None
    m = STYLE_RE.search(doc)
    if not m:
        return None
    if m.group(2) == CSS:
        return False
    with open(path, "w", encoding="utf-8") as f:
        f.write(doc[:m.start(2)] + CSS + doc[m.end(2):])
    return True


def main(argv):
    check = "--check" in argv[1:]
    own = {p for p, _ in dash.NAV}
    changed, skipped = [], []
    for name in sorted(os.listdir(REPORTS_DIR)):
        if not name.endswith(".html") or name in own:
            continue
        path = os.path.join(REPORTS_DIR, name)
        if check:
            with open(path, encoding="utf-8") as f:
                doc = f.read()
            m = STYLE_RE.search(doc)
            if SHELL_MARK not in doc or not m:
                skipped.append(name)
                continue
            if m.group(2) != CSS:
                changed.append(name)
            continue
        result = restyle(path)
        if result is None:
            skipped.append(name)
        elif result:
            changed.append(name)

    verb = "stale" if check else "restyled"
    print(f"{len(changed)} report(s) {verb}"
          + (": " + ", ".join(changed) if changed else ""))
    if skipped:
        print(f"{len(skipped)} file(s) skipped (not produced by html_shell): "
              + ", ".join(skipped))
    return 1 if (check and changed) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
